### ISSUE TITLE
No provisions for `strip`ping binaries

### ISSUE THREAD

**Issue by username223** [ebbflow-io/cargo-deb-armv7-debian#2]
The default `strip` tool on `x86` can not strip `armv7` binaries.

An `armv7` stripper can be found on Debian in the `binutils-arm-linux-gnueabihf` package and used with `arm-linux-gnueabihf-strip`.

In order to configure this with `cargo deb`, `strip = { path = "arm-linux-gnueabihf-strip" }` should be added to the `~/.cargo/config` file under the `[target.armv7-unknown-linux-musleabihf]` header.

This would enable the image to strip binaries by deafult, like the `amd64` image.

A temporary workaround is to install `binutils-arm-linux-gnueabihf` and append to the config file:
```sh
apt install binutils-arm-linux-gnueabihf
# Most recent toml header is [target.armv7-unknown-linux-musleabihf]
echo 'strip = { path = \"arm-linux-gnueabihf-strip\" }' >> /root/.cargo/config
```

**Comment by gorup** [comment]
Hi! Thanks for this. Yeah I had `--no-strip` because I didn't know the best way to fix that and I just wanted to launch the project I am working on.

But thanks to this message, I looked into it, and was able to actually use the `musl` strip tool and that is made available when I build `musl`. 

After running `file` on an executable that is part of my `.deb`, I got the following input which shows the stripping worked

```
ebbflow: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

New version will be released once the builds finish!

**Comment by gorup** [comment]
New version released after building and testing, closing the issue, let me know if you have questions!

**Comment by username223** [comment]
Thanks for the fix.

Just a heads up, the [README](https://github.com/ebbflow-io/cargo-deb-armv7-debian/blob/bec0ba8f9a4bea7af94001bd9d2fc8e52d15ee90/README.md#L22) still says that `--no-strip` is the default action.

**Comment by gorup** [comment]
ok yeah I will update that, thanks!
